---
apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: a-build
  annotations:
    build.build.dev/build-run-deletion: "true"
spec:
  source:
    url: https://github.com/shipwright-io/build
  paramValues:
  - name: filepath
    value: ".github/draft_release_notes.sh"
  - name: args
    values:
    - value: "--color=auto"
    - configMapValue:
       name: format
       key: formattype
  strategy:
    name: a-strategy
    kind: ClusterBuildStrategy
  output:
    image: docker.io/eeeoo/sample:latest
    credentials:
      name: example-secret