---
apiVersion: shipwright.io/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: a-strategy
spec:
  parameters:
  - name: filepath
    description: "Path to file"
    type: string
  - name: args
    description: "Arguments to pass to the shellcheck binary"
    type: array
    defaults: []
  buildSteps:
    - name: check-script
      image: docker.io/koalaman/shellcheck:v0.7.1@sha256:ad95c140f7bf5cc66e50e19da7d72c398583ba24c5866ac32c882eb3ddc153ee
      command:
        - /bin/shellcheck
      args:
        - $(params.args[*])
        - $(params.shp-source-context)/$(params.filepath)